// js/physics.js

const Physics = {
    // Constants
    G: 9.81,            // Gravity (m/s^2)
    RHO: 1.225,         // Air density (kg/m^3) at sea level
    CDA: 0.32,          // Aerodynamic drag coefficient x frontal area (m^2) - typical for hoods
    CRR: 0.004,         // Rolling resistance coefficient - typical for good tarmac
    DRIVETRAIN_EFFICIENCY: 0.97, // 3% loss

    // Assumed weights
    RIDER_WEIGHT: 75,   // kg
    BIKE_WEIGHT: 8,     // kg

    // Current state
    velocity: 0,        // m/s

    /**
     * Calculate instantaneous speed based on power, grade, and current velocity.
     * This uses a discrete time step approximation of the equations of motion.
     *
     * @param {number} power Watts generated by rider
     * @param {number} gradePercent Current incline percentage (e.g. 5 for 5%)
     * @param {number} dt Time step in seconds (e.g., 1 for 1Hz)
     * @returns {number} Speed in km/h
     */
    calculateSpeedKmh(power, gradePercent, dt = 1) {
        const totalMass = this.RIDER_WEIGHT + this.BIKE_WEIGHT;
        const slopeAngle = Math.atan(gradePercent / 100);

        // Forces resisting motion
        // 1. Gravity (Incline)
        const fGravity = totalMass * this.G * Math.sin(slopeAngle);

        // 2. Rolling Resistance
        const fRolling = totalMass * this.G * Math.cos(slopeAngle) * this.CRR;

        // 3. Aerodynamic Drag
        const fDrag = 0.5 * this.RHO * this.CDA * Math.pow(this.velocity, 2);

        const totalResistingForce = fGravity + fRolling + fDrag;

        // Force generated by rider
        // Power = Force * Velocity => Force = Power / Velocity
        // Handle velocity = 0 case to avoid divide by zero
        let fRider = 0;
        const effectivePower = power * this.DRIVETRAIN_EFFICIENCY;

        if (this.velocity > 0.1) {
            fRider = effectivePower / this.velocity;
        } else {
            // When starting from rest, acceleration is primarily limited by max torque,
            // but we can approximate a starting force.
            fRider = effectivePower / 0.1;
        }

        // Net force and acceleration
        // F = ma => a = F/m
        const netForce = fRider - totalResistingForce;
        const acceleration = netForce / totalMass;

        // Update velocity (v = u + at)
        this.velocity = this.velocity + (acceleration * dt);

        // Prevent negative velocity (moving backwards)
        if (this.velocity < 0) {
            this.velocity = 0;
        }

        // Convert m/s to km/h
        return this.velocity * 3.6;
    }
};
